### PR TITLE
add support for abbrv param

### PR DESCRIPTION
**Pull request by freyfogle**
see: http://blog.opencagedata.com/post/160294347883/shrtr-pls

### CODE REVIEW

**Comment by maelle** [comment]
Thanks. If the parameter is used for an unsupported language, it's just ignored, right?

**Comment by freyfogle** [comment]
yes it is just ignored if that language is not yet supported

**Comment by maelle** [comment]
ok thanks, I'll merge& add a few lines code&doc and a test later today/tomorrow.

**Comment by freyfogle** [comment]
thanks. no rush

**Comment by maelle** [comment]
Once I'll have repaired the package (my fault, not updating documentation), I'll submit a new version to CRAN soon, probably tomorrow.

**Comment by maelle** [comment]
New version on CRAN :tada: will tweet once the CRAN link works again.

**Comment by freyfogle** [comment]
moltes gràcies

**Pull request merged**
