### PR TITLE
Nested tibbles instead of df_list output

### PR DESCRIPTION
**Pull request by charliejhadley**
As a user of `{opencage}` I'm very much looking forward to the devel version of the package, particularly the new vectorised functions. However, in testing the package I found the default `df_list` output format to be troublesome.

This PR updates all versions of `oc_forward*()` and `oc_reverse*()` to output tibbles with OpenCage columns nested into the `data` column. The tests have also been updated to anticipate nested tibbles instead of a list of tibbles.

I realise this PR wasn't requested, and might not be considered useful. However, I believe that by outputting nested tibbles the package is more in-keeping with current tidyverse style guides. Switching to nested tibbles has allowed some of the internal logic to be simplified and has also removed the need to check {tidyr} versions before internal unnesting.

There's also the issue of duplicate column names in the `oc_*_df()` functions. By keeping the OpenCage nested the user is then responsible for providing `unnest()` with a renaming scheme. I believe that's beneficial as internal renaming logic could likely cause confusion as the data columns from OpenCage are already prefixed with `oc_`

### CODE REVIEW

**Comment by dpprdan** [comment]
@charliejhadley Thanks a lot! 🎉 We'll definitely check this out. Unfortunately, I cannot commit to anything for this week or next, though, so this might take a little while.

**Comment by charliejhadley** [comment]
No worries, @dpprdan.

**Comment by dpprdan** [comment]
Sorry, @charliejhadley for taking so long and thanks again for your contribution!

Unfortunately, I am a bit doubtful about whether I support this PR in general, mostly because I don't see exactly how it improves the status quo. I do see its appeal in that it makes the default return value of `oc_forward()` probably easier to handle. ("Probably", because I am not 100% sure whether list columns are always easier to handle for not-so-experienced R users than a list of data frames. E.g. `bind_rows()` might be easier to understand conceptually than `unnest()`). But for easier-to-handle-return-values we already have the `_df` functions, so `oc_forward()` output being slightly more difficult to handle is not a major problem IMO. 

The change in the default return value is also my main concern with this PR. We designed `oc_forward()` as a (relatively) low-level function and `oc_forward_df()` as a (more) high-level function. `oc_forward()` returns lists of results in different formats with (arguably) as few adjustments as possible. `oc_forward_df()` OTOH returns a formatted tibble which doesn't require any more post-processing. With `oc_forward(return = "tibble")` we now get a hybrid, that returns a tibble which requires some post-processing. As a result, it is not possible/easy to use `oc_forward(return = "tibble")` within a `mutate()` statement anymore for example. (dplyr pre v1.0 will throw an error IIRC, v1.0+ will return a tibble column which is not straightforward to handle as of yet IMO.) As a result, we loose some flexibility here.

> I found the default `df_list` output format to be troublesome.

Could you elaborate on that? What exactly did you find troublesome? From my perspective it is relatively easy to get output with nested tibbles without your PR.

``` r
library(tibble)
library(opencage)
locations <- c("Hamburg", "Nancy", "Los Angeles")
tibble(oc_query = locations, data = oc_forward(locations, return = "df_list"))
#> # A tibble: 3 x 2
#>   oc_query    data              
#>   <chr>       <list>            
#> 1 Hamburg     <tibble [8 x 22]> 
#> 2 Nancy       <tibble [9 x 29]> 
#> 3 Los Angeles <tibble [10 x 27]>
```

As an aside, I am not entirely convinced that nested tibbles adhere more to current tidyverse coding styles, see e.g. [`dplyr::group_map()`](https://dplyr.tidyverse.org/reference/group_map.html). 

Apart from these more general concerns I also have some more specific comments:
  
1. Currently duplicates are not handled well: `oc_forward(c("Hamburg", "Nancy", "Hamburg"))` returns only two rows. As a result `oc_forward_df(c("Hamburg", "Nancy", "Hamburg"))` throws an error. 
2. `oc_forward_df()`, returns a list column as well. Since it also allows character vectors as input, there is not much of a difference between `oc_forward("Hamburg")` and `oc_forward_df("Hamburg")` (except for a difference in defaults). Since `oc_forward_df()` is meant to be _the_ function to get quick geocoding results, no further wrangling should be necessary to see the full results, i.e. the results should be unnested already. (And then we need to check {tidyr} versions, again, unless we bump the tidyr requirement to >= v1.0).
3. Documentation says that oc_forward returns a list of tibbles (see `@return`). Instead oc_forward/_reverse now return either a tibble with a list column or a list. So instead of having the same primary return type, a list, we now have two.
4. I'd name the list column with the results `oc_results` or similar instead of `data`. `data` is (more) ambiguous (than `oc_results`), since we use `data` in the tidyeval statements (e.g. the `eval_tidy()` calls in `oc_forward_df()`) as well. 
5. The `oc_query` column in the `_df` result is redundant and should be omitted there.
6. The `if (bind_cols == FALSE) {` conditional is mostly redundant at this moment (which might change depending on the other points raised here), since the only difference between both code blocks is `results <- dplyr::bind_cols(data, oc_results)` which could also be done after the `output == "short"` statements. Something along the lines of `if (bind_cols == FALSE) {return(results)} else {dplyr::bind_cols(data, results)}`. 

In sum, I cannot accept this PR at the moment, unfortunately. If you want to pursue it further, I'd suggest that we discuss the general idea behind it some more before fixing the more specific issues mentioned.

**Comment by dpprdan** [comment]
Closing this for the reasons mentioned above.

**Pull request closed without merging**
