### PR TITLE
Clean up tests

### PR DESCRIPTION
**Pull request by dpprdan**
This cleans up/fixes some tests to reflect the changes in the devel branch until now (i.e. up until April).

### CODE REVIEW

**Comment by jessesadler** [comment]
It looks like the CI tests are failing in building the vignette on trying to create a key. Is this related to the changes to always require a key? We will also need to significantly rewrite the vignettes, so whether the vignette builds or not does not seem like a very big deal right now.

**Comment by dpprdan** [comment]
I have not looked into the Travis errors, yet. @maelle there is an OpenCage key provided on Travis, right? I.e. it should in principle be possible to build a (valid) vignette there? 

I get the appveyor warnings also on my machine. But these are not due to code that I changed in this PR, but due to missing documentation and should also fail on the current devel branch. Is it possible to see appveyor results for current branches other than master in the main repo?

@jessesadler if you have time, could you take a look at the following NOTE? 

```r
* checking R code for possible problems ... NOTE
oc_forward_df: no visible binding for global variable 'query'
oc_forward_df: no visible binding for global variable 'lat'
oc_forward_df: no visible binding for global variable 'lng'
oc_forward_df: no visible binding for global variable 'formatted'
oc_reverse_df: no visible binding for global variable 'query'
oc_reverse_df: no visible binding for global variable 'formatted'
Undefined global functions or variables:
  formatted lat lng query
```

You should get the same when you do a R Cmd Check on the devel branch and I also still get it on my current branch. My google fu returned this: https://github.com/STAT545-UBC/Discussion/issues/451

**Review by maelle — APPROVED** [review]
Thanks!

Reg the note maybe add variables to https://github.com/ropensci/opencage/blob/8bf3b6257b20da34893f287930cece13108aecd8/R/globalVariables.R

**Comment by jessesadler** [comment]
@dpprdan The notes are showing because `R CMD check` does not know that they are columns from a data frame when using `dplyr::select()`. The two ways I have found to deal with this is either `.data` from `rlang` in which you do `.data$lat` etc. or as @maelle noted we can just put them in globalVariables.R. The latter would seem to me preferable since you did all of the evaluation of the data frame variables for the `pmap` branch in base and not in tidyeval with `rlang`.

Here is the documentation for `.data` if you want to take a look: https://rlang.r-lib.org/reference/tidyeval-data.html

**Comment by dpprdan** [comment]
TBH the evaluation of the data frame variables part is the one I am most unsure about, i.e. whether this is the proper way to allow vectors, lists, and data frame columns. But I wouldn't know how to do this with rlang ATM.

But anyway, I added the objects to globalVariables and the NOTE is gone on my local R CMD check and on AppVeyor as well. There are still the warnings (treated as errors) due to the missing documentation, so AppVeyor does not proceed any further than before. 

I only see now that Travis clearly states that "no environment variable [are] set", so it is not surprising that no key is found and `oc_check_query()` is complaining about it. 

In the [Job log](https://travis-ci.org/ropensci/opencage/jobs/437342463) it says "Encrypted environment variables have been removed for security reasons." The relevant [Travis docs](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions) than state that this is because the PR is coming from a third-party repo (as far as Travis is concerned), which could try to maliciously expose the env vars. [UPDATE:] If I understand correctly, the only way around this would be to issue the PR ~as the ropensci user~ in the ropensci repo, but I don't know how to do this (i.e. not merge directly).

@maelle Do you have any idea how to solve this? Did this come up in ropensci before?

(The docs also mention how to disable Travis for third-party PRs, which seems like a reasonable move given that our builds will most likely always depend on env vars?)

Anyway I will merge this PR now, given that my local R CMD check works (except for the two documentation warnings).

**Comment by dpprdan** [comment]
Re "If I understand correctly, the only way around this would be to issue the PR in the ropensci repo."

The way to do this is to push to the ropensci repo and create the PR from the [compare page](https://github.com/ropensci/opencage/compare), I suppose?!

**Pull request merged**
