### PR TITLE
 refactoring code and new functions oc_forward and oc_reverse 

### PR DESCRIPTION
**Pull request by dpprdan**
For some reason (well Sourcetree says I lack the permission) I cannot push to devel. So this is a PR with some code refactoring and the new oc_forward and oc_reverse functions.

### CODE REVIEW

**Comment by maelle** [comment]
Fantastic, many thanks! 😃  Including reg the white spaces that you have added 😍  I guess I could even uncomment the `lintr` test now.

 I prefer not having importFrom in NAMESPACE and always using "::", I'll merge once you've removed that. I should have written it somewhere, sorry!

A few remarks for your next commits :wink: (even after the merge for these ones) :

* you can replace "ctb" with "aut" for your entry in DESCRIPTION

* a few commits down the road we'll update NEWS and also the version number in DESCRIPTION

**Comment by maelle** [comment]
Actually I'll merge and trust you to change the importFrom.

**Comment by dpprdan** [comment]
> I prefer not having importFrom in NAMESPACE and always using "::", I'll merge once you've removed that. I should have written it somewhere, sorry!

Will do. Just out of curiosity, what's the problem with importFrom? I thought that's what Hadley recommends in http://r-pkgs.had.co.nz/namespace.html. 

>  I guess I could even uncomment the lintr test now.
Will try. Haven't worked with lintr, yet, though.

**Comment by maelle** [comment]
Good question! I like seeing in the code where the functions come from. In my `ropenaq` package I was glad for instance when I replaced `httr` with `crul` to easily find where work was needed.

The book actually says "It’s common for packages to be listed in Imports in DESCRIPTION, but not in NAMESPACE. In fact, this is what I recommend: list the package in DESCRIPTION so that it’s installed, then always refer to it explicitly with pkg::fun(). Unless there is a strong reason not to, it’s better to be explicit. It’s a little more work to write, but a lot easier to read when you come back to the code in the future.."

**Comment by dpprdan** [comment]
Oh, I see. I should have read all the way down to "Imports". 😸 
I think I may have played it extra safe here. I use `::`, `@importFrom` (at every pkg function that uses an imported function), and the packages are also in DESCRIPTION. Actually they have to be in DESCRIPTION if they are in NAMESPACE, otherwise R CMD CHECK will error. That cost me half an hour last night, because the error message was not very informative IMO (I used `@importFrom purrr compact`, but had not added purrr to DESCRIPTION). 

FYI see Colin Fay's blog post on [random benchmarks](http://colinfay.me/random-r-benchmarks/): "Use importFrom, not ::" But then again, developer time is more valuable than computer time.

Will remove the `@importFrom`s

**Comment by maelle** [comment]
Thanks! Yes I saw Colin's cool post. 

I recently re read the whole book as prep work for a course! It's dense and will be updated this year so we'll all have to read it again 😂

I am so into "::" these days that I use it when blogging to show the reader what does what, I tend to only load `magrittr` and `ggplot2`. But I'm sorry for the time loss and again thanks a lot!

**Comment by dpprdan** [comment]
`@importFrom`s removed.
> But I'm sorry for the time loss and again thanks a lot!
No problem. I am glad to learn and to have a great mentor! 😄

**Comment by dpprdan** [comment]
pinging @jessesadler re: the importFrom discussion, in case you did not see this already.

**Pull request merged**
